### ISSUE TITLE
Hard coded images Busybox and Curl

### ISSUE THREAD

**Issue by hulljaja** [Alfresco/alfresco-helm-charts#397]
Please factor out hard coded images like busybox and curl and make them configurable in the values.yaml.

**Comment by gionn** [comment]
It might be beneficial to make these configurable, allowing for the use of specific images when needed, instead of relying on the default ones (e.g. air gapped environments or need to use alternate images).

If you'd like to prioritize this and have it implemented sooner, feel free to raise a PR.

This has been internally tracked as OPSEXP-2900.
